import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const SYSTEMS=[
{id:'skeletal',name:'Skeleton',color:'#d8cfb6'},
{id:'muscular',name:'Muscles',color:'#a85b50'},
{id:'cardiac',name:'Heart',color:'#9d4f45'},
{id:'sensory',name:'Sensory organs',color:'#91aeb2'},
{id:'arterial',name:'Arteries',color:'#b95345'},
{id:'venous',name:'Veins',color:'#527c9f'},
{id:'nervous',name:'Nervous system',color:'#d8b565'},
{id:'respiratory',name:'Respiratory',color:'#b98991'},
{id:'digestive',name:'Digestive',color:'#b8916b'},
{id:'urinary',name:'Urinary',color:'#88738f'},
{id:'lymphatic',name:'Lymphatic',color:'#879f7c'},
{id:'endocrine',name:'Endocrine',color:'#c5a09a'},
{id:'reproductive',name:'Reproductive',color:'#bda098'},
{id:'integumentary',name:'Body surface',color:'#ba9b7d'},
{id:'connective',name:'Connective tissue',color:'#aec3bb'},
{id:'other',name:'Other anatomy',color:'#9da5a3'}];
const SYSTEM_MAP=new Map(SYSTEMS.map((s,i)=>[s.id,{...s,index:i}]));
const ORGANS=new Set(['cardiac','respiratory','digestive','urinary','endocrine','reproductive']);
const state={atlas:null,visible:new Set(),selected:null,isolate:false,targetExplode:0,explode:0,view:'three-quarter',rotate:false,ready:false};

const $=s=>document.querySelector(s);
const host=$('#scene'),systemList=$('#system-list'),visibleCount=$('#visible-count'),systemCount=$('#system-count'),modelCount=$('#model-count'),explodeInput=$('#explode'),explodeOutput=$('#explode-output'),caption=$('#scene-caption b'),loading=$('#loading'),loadingBar=$('#loading-bar'),loadingCopy=$('#loading-copy'),detail=$('#detail'),detailName=$('#detail-name'),detailSystem=$('#detail-system'),detailAccent=$('#detail-accent'),detailSummary=$('#detail-summary'),detailId=$('#detail-id'),detailConcept=$('#detail-concept'),searchModal=$('#search-modal'),searchInput=$('#search-input'),searchResults=$('#search-results'),aboutModal=$('#about-modal'),app=$('#app');

const scene=new THREE.Scene();scene.background=new THREE.Color('#f2f3f3');
const camera=new THREE.PerspectiveCamera(34,1,.005,100);camera.position.set(1.4,1.05,3.6);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.setClearColor('#f2f3f3');host.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.85,0);controls.enableDamping=true;controls.dampingFactor=.085;controls.minDistance=.07;controls.maxDistance=40;controls.maxPolarAngle=Math.PI*.96;
scene.add(new THREE.HemisphereLight(0xffffff,0xa7acb2,1.05));const key=new THREE.DirectionalLight(0xfffaf4,2.3);key.position.set(-2,4,3);scene.add(key);const rim=new THREE.DirectionalLight(0xe9f0ff,1.8);rim.position.set(2,2,-3);scene.add(rim);
const ground=new THREE.Mesh(new THREE.CircleGeometry(30,96),new THREE.MeshStandardMaterial({color:0xd5d9dc,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.019;scene.add(ground);
const platform=new THREE.Mesh(new THREE.CylinderGeometry(.68,.7,.028,100),new THREE.MeshStandardMaterial({color:0xeeeeec,metalness:.12,roughness:.67}));platform.position.y=-.016;scene.add(platform);
const ring=new THREE.Mesh(new THREE.RingGeometry(.63,.632,128),new THREE.MeshBasicMaterial({color:0x8c969f,transparent:true,opacity:.4,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.001;scene.add(ring);

const batches=new Map(),handles=[],centers=[],bounds=[],offsets=[],packedOffsets=[];let packingWidth=1,packingHeight=1,layoutKey='';
const identity=new THREE.Matrix4(),matrix=new THREE.Matrix4();

async function fetchBinary(url){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw new Error(`Could not load ${url}`);const ab=await r.arrayBuffer(),u=new Uint8Array(ab);if(u[0]===0x1f&&u[1]===0x8b){if(typeof DecompressionStream==='undefined')throw new Error('This browser cannot decompress the anatomy package.');return new Response(new Blob([ab]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer()}return ab}
function geometryFromPart(buffer,p){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(new Float32Array(buffer,p.positions,p.vertexCount*3),3));g.setAttribute('normal',new THREE.BufferAttribute(new Int16Array(buffer,p.normals,p.vertexCount*3),3,true));g.setIndex(new THREE.BufferAttribute(new Uint32Array(buffer,p.indices,p.indexCount),1));g.boundingBox=new THREE.Box3(new THREE.Vector3(...p.bounds[0]),new THREE.Vector3(...p.bounds[1]));g.computeBoundingSphere();return g}
function createBatches(atlas){for(const [system,s] of Object.entries(atlas.systemStats||{})){const meta=SYSTEM_MAP.get(system)||SYSTEM_MAP.get('other');const mat=new THREE.MeshStandardMaterial({color:meta.color,metalness:.08,roughness:.53,side:THREE.DoubleSide,transparent:system==='integumentary',opacity:system==='integumentary'?.12:1,depthWrite:system!=='integumentary'});const b=new THREE.BatchedMesh(Math.max(1,s.parts+2),Math.ceil(s.vertices*1.01)+16,Math.ceil(s.indices*1.01)+48,mat);b.frustumCulled=false;b.perObjectFrustumCulled=true;b.userData.instanceToPart=[];batches.set(system,b);scene.add(b)}}

function visibleParts(){return state.atlas.parts.map((p,i)=>({p,i})).filter(({p,i})=>state.isolate?i===state.selected:state.visible.has(p.system)||i===state.selected)}
function createExplosionLayout(items,aspect=1){const cards=items.map(({p,i})=>({i,width:Math.max(.035,p.bounds[1][0]-p.bounds[0][0])+.04,height:Math.max(.035,p.bounds[1][1]-p.bounds[0][1])+.04}));const area=cards.reduce((n,c)=>n+c.width*c.height,0),maxWidth=Math.max(.3,...cards.map(c=>c.width));const targetWidth=Math.max(maxWidth,Math.sqrt(area*Math.max(.5,Math.min(1.5,aspect)))*1.18);cards.sort((a,b)=>b.height-a.height||a.i-b.i);const cells=new Map();let x=0,y=0,row=0,usedWidth=0;for(const c of cards){if(x>0&&x+c.width>targetWidth){x=0;y+=row;row=0}cells.set(c.i,{x:x+c.width/2,y:-y-c.height/2});x+=c.width;usedWidth=Math.max(usedWidth,x);row=Math.max(row,c.height)}const height=y+row;cells.forEach(c=>{c.x-=usedWidth/2;c.y+=height/2});return{cells,width:usedWidth,height}}
function rebuildLayout(){if(!state.atlas)return;const items=visibleParts(),key=items.map(x=>x.i).join(',')+':'+camera.aspect.toFixed(2);if(key===layoutKey)return;const layout=createExplosionLayout(items,camera.aspect);packingWidth=layout.width;packingHeight=layout.height;for(let i=0;i<state.atlas.parts.length;i++){const cell=layout.cells.get(i);packedOffsets[i]=cell?new THREE.Vector3(cell.x-centers[i].x,cell.y+.85-centers[i].y,-centers[i].z):new THREE.Vector3()}layoutKey=key}
function targetOffset(i){if(!state.atlas)return new THREE.Vector3();const p=state.atlas.parts[i],c=centers[i],amount=state.explode;if(amount<=.001)return new THREE.Vector3();const group=(SYSTEM_MAP.get(p.system)?.index??SYSTEMS.length-1),angle=group/SYSTEMS.length*Math.PI*2;const radial=new THREE.Vector3(Math.sin(angle)*.48,(c.y-.85)*.28,Math.cos(angle)*.48);if(amount<=.45)return radial.multiplyScalar(amount/.45);const t=(amount-.45)/.55;return radial.lerp(packedOffsets[i]||new THREE.Vector3(),t)}
function updateSceneState(){if(!state.ready)return;rebuildLayout();for(let i=0;i<state.atlas.parts.length;i++){const p=state.atlas.parts[i],h=handles[i];if(!h)continue;const show=state.isolate?i===state.selected:state.visible.has(p.system)||i===state.selected;h.batch.setVisibleAt?.(h.instanceId,show);const off=targetOffset(i);offsets[i].lerp(off,.22);matrix.makeTranslation(offsets[i].x,offsets[i].y,offsets[i].z);h.batch.setMatrixAt(h.instanceId,matrix);const base=new THREE.Color(SYSTEM_MAP.get(p.system)?.color||'#9da5a3');if(i===state.selected)base.lerp(new THREE.Color('#69d8c8'),.72);h.batch.setColorAt(h.instanceId,base)}updateCounts();updateCaption();app.classList.toggle('inventory-mode',state.explode>.8)}

function bodyMetrics(){const b=state.atlas.bounds;return{low:b[0],high:b[1],height:b[1][1]-b[0][1]}}
function fitView(view=state.view,extent=state.explode){if(!state.atlas)return;const {low,high,height}=bodyMetrics();const center=new THREE.Vector3((low[0]+high[0])/2,(low[1]+high[1])/2,(low[2]+high[2])/2);let target=center.clone().add(new THREE.Vector3(0,height*.01,0)),distance=height*2.1;if(extent>.55){const fov=THREE.MathUtils.degToRad(camera.fov),need=Math.max(packingHeight,packingWidth/Math.max(.55,camera.aspect));distance=Math.max(2,need/(2*Math.tan(fov/2))*1.12);target.set(0,.85,0);if(extent>.8)view='front'}const dir=view==='front'?new THREE.Vector3(0,.02,1):view==='back'?new THREE.Vector3(0,.02,-1):view==='side'?new THREE.Vector3(1,.02,0):new THREE.Vector3(.35,.06,1).normalize();controls.target.copy(target);camera.position.copy(target).addScaledVector(dir,distance);controls.update()}
function setView(view){state.view=view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));fitView(view,state.explode)}

function renderSystems(){if(!state.atlas)return;systemList.replaceChildren();const counts=new Map();for(const p of state.atlas.parts)counts.set(p.system,(counts.get(p.system)||0)+1);const active=SYSTEMS.filter(s=>counts.get(s.id));systemCount.textContent=active.length;for(const s of active){const row=document.createElement('div');row.className='system-row';const name=document.createElement('button');name.className='system-name';name.innerHTML=`<span class="system-dot" style="background:${s.color}"></span><span>${s.name}</span><span class="system-count">${counts.get(s.id)}</span>`;name.onclick=()=>{state.visible=new Set([s.id]);state.isolate=false;state.selected=null;layoutKey='';syncDetail();renderSystems();updateSceneState()};const toggle=document.createElement('button');toggle.className='toggle'+(state.visible.has(s.id)?' on':'');toggle.innerHTML='<i></i>';toggle.onclick=()=>{state.visible.has(s.id)?state.visible.delete(s.id):state.visible.add(s.id);state.isolate=false;layoutKey='';renderSystems();updateSceneState()};row.append(name,toggle);systemList.appendChild(row)}}
function updateCounts(){if(!state.atlas)return;let count=0;state.atlas.parts.forEach((p,i)=>{if(state.isolate?i===state.selected:state.visible.has(p.system)||i===state.selected)count++});visibleCount.textContent=count.toLocaleString()}
function updateCaption(){caption.textContent=state.isolate?'SELECTED STRUCTURE':state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':'ADULT HUMAN · MALE';$('#interaction-hint').textContent=state.explode>.8?'Drag to pan · Pinch to zoom · Tap to inspect':'Drag to orbit · Pinch to zoom · Tap to inspect'}

function selectPart(index,{focus=false}={}){if(index==null||!state.atlas.parts[index])return;state.selected=index;state.isolate=false;const p=state.atlas.parts[index],meta=SYSTEM_MAP.get(p.system)||SYSTEM_MAP.get('other');detailName.textContent=p.name;detailSystem.textContent=meta.name.toUpperCase();detailAccent.style.background=meta.color;detailSummary.textContent=`${meta.name} structure from the BodyParts3D adult male reference anatomy.`;detailId.textContent=p.elementId||p.id;detailConcept.textContent=p.conceptId||'—';detail.classList.add('open');updateSceneState();if(focus)focusSelection()}
function syncDetail(){if(state.selected==null)detail.classList.remove('open')}
function focusSelection(){if(state.selected==null)return;const i=state.selected,c=centers[i].clone().add(offsets[i]),r=Math.max(.03,bounds[i].getBoundingSphere(new THREE.Sphere()).radius),dir=camera.position.clone().sub(controls.target).normalize();controls.target.copy(c);camera.position.copy(c).addScaledVector(dir,Math.max(.25,Math.min(2.8,r*6.5)));controls.update()}

const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null,hover=null;
function ensureHover(){if(hover)return hover;hover=document.createElement('div');hover.className='part-hover';hover.hidden=true;host.appendChild(hover);return hover}
renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY}});
renderer.domElement.addEventListener('pointermove',e=>{if(!state.ready||e.buttons)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects([...batches.values()],false),hit=hits.find(x=>(x.batchId??x.instanceId)!=null);const h=ensureHover();if(!hit){h.hidden=true;renderer.domElement.style.cursor='grab';return}const id=hit.batchId??hit.instanceId,index=hit.object.userData.instanceToPart[id];if(index==null){h.hidden=true;return}h.textContent=state.atlas.parts[index].name;h.style.left=Math.min(e.clientX-rect.left+14,rect.width-220)+'px';h.style.top=Math.min(e.clientY-rect.top+16,rect.height-40)+'px';h.hidden=false;renderer.domElement.style.cursor='pointer'});
renderer.domElement.addEventListener('pointerup',e=>{if(!state.ready||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>7)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects([...batches.values()],false),hit=hits.find(x=>(x.batchId??x.instanceId)!=null);if(hit){const id=hit.batchId??hit.instanceId,index=hit.object.userData.instanceToPart[id];if(index!=null)selectPart(index)}});

function renderSearch(){if(!state.atlas)return;const q=searchInput.value.trim().toLowerCase();let rows=state.atlas.parts.map((p,i)=>({p,i})).filter(({p})=>!q||p.name.toLowerCase().includes(q)||String(p.elementId||'').toLowerCase().includes(q)||String(p.conceptId||'').toLowerCase().includes(q));rows=rows.sort((a,b)=>a.p.name.length-b.p.name.length).slice(0,80);searchResults.replaceChildren(...rows.map(({p,i})=>{const b=document.createElement('button');b.innerHTML=`<span>${p.name}</span><small>${p.elementId||p.id}</small>`;b.onclick=()=>{searchModal.hidden=true;selectPart(i,{focus:true})};return b}))}

function applyPreset(preset){const ids=SYSTEMS.filter(s=>state.atlas.systemStats?.[s.id]).map(s=>s.id);if(preset==='all')state.visible=new Set(ids.filter(x=>x!=='integumentary'));if(preset==='skeleton')state.visible=new Set(['skeletal']);if(preset==='organs')state.visible=new Set(ids.filter(x=>ORGANS.has(x)));state.selected=null;state.isolate=false;layoutKey='';document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===preset));renderSystems();syncDetail();updateSceneState()}
function resetAll(){state.targetExplode=0;state.explode=0;explodeInput.value='0';explodeOutput.innerHTML='0<span>%</span>';state.rotate=false;controls.autoRotate=false;state.selected=null;state.isolate=false;applyPreset('all');setView('three-quarter');detail.classList.remove('open')}

explodeInput.addEventListener('input',()=>{state.targetExplode=Number(explodeInput.value)/100;explodeOutput.innerHTML=`${explodeInput.value}<span>%</span>`;if(state.targetExplode>.8)setView('front')});explodeInput.addEventListener('change',()=>{rebuildLayout();fitView(state.targetExplode>.8?'front':state.view,state.targetExplode)});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
$('#rotate-view').onclick=()=>{state.rotate=!state.rotate;controls.autoRotate=state.rotate;controls.autoRotateSpeed=1.1;$('#rotate-view').classList.toggle('active',state.rotate)};
$('#reset-view').onclick=()=>fitView(state.view,state.explode);$('#assemble-reset').onclick=resetAll;$('#detail-close').onclick=()=>{state.selected=null;state.isolate=false;detail.classList.remove('open');updateSceneState()};$('#focus-selection').onclick=focusSelection;$('#isolate-selection').onclick=()=>{if(state.selected==null)return;state.isolate=!state.isolate;state.targetExplode=0;explodeInput.value='0';explodeOutput.innerHTML='0<span>%</span>';layoutKey='';$('#isolate-selection').textContent=state.isolate?'◎ Show surroundings':'◎ Isolate structure';updateSceneState();fitView('three-quarter',0)};$('#hide-all').onclick=()=>{state.visible.clear();state.selected=null;state.isolate=false;layoutKey='';renderSystems();syncDetail();updateSceneState()};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));
$('#search-open').onclick=()=>{searchModal.hidden=false;searchInput.focus();renderSearch()};searchInput.oninput=renderSearch;document.querySelectorAll('[data-close="search"]').forEach(b=>b.onclick=()=>searchModal.hidden=true);$('#about-open').onclick=$('#credits-open').onclick=()=>aboutModal.hidden=false;document.querySelectorAll('[data-close="about"]').forEach(b=>b.onclick=()=>aboutModal.hidden=true);window.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement?.tagName!=='INPUT'){e.preventDefault();searchModal.hidden=false;searchInput.focus();renderSearch()}if(e.key==='Escape'){searchModal.hidden=true;aboutModal.hidden=true}});

new ResizeObserver(()=>{const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);layoutKey=''}).observe(host);

async function loadAtlas(atlas){state.atlas=atlas;modelCount.textContent=atlas.parts.length.toLocaleString();createBatches(atlas);atlas.parts.forEach((p,i)=>{const a=p.bounds[0],b=p.bounds[1];centers[i]=new THREE.Vector3((a[0]+b[0])/2,(a[1]+b[1])/2,(a[2]+b[2])/2);bounds[i]=new THREE.Box3(new THREE.Vector3(...a),new THREE.Vector3(...b));offsets[i]=new THREE.Vector3();packedOffsets[i]=new THREE.Vector3()});const byChunk=Array.from({length:atlas.chunks.length},()=>[]);atlas.parts.forEach((p,i)=>byChunk[p.chunk].push([i,p]));let loaded=0,cursor=0;async function worker(){while(cursor<atlas.chunks.length){const ci=cursor++,buffer=await fetchBinary(atlas.chunks[ci].url);for(const [i,p] of byChunk[ci]){const batch=batches.get(p.system);if(!batch)continue;const g=geometryFromPart(buffer,p),gid=batch.addGeometry(g),iid=batch.addInstance(gid);batch.setMatrixAt(iid,identity);batch.setColorAt(iid,new THREE.Color(SYSTEM_MAP.get(p.system)?.color||'#9da5a3'));batch.userData.instanceToPart[iid]=i;handles[i]={batch,instanceId:iid};g.dispose()}loaded++;const pct=Math.round(loaded/atlas.chunks.length*100);loadingBar.style.width=pct+'%';loadingCopy.textContent=`${pct}% · Loading ${atlas.parts.length.toLocaleString()} pieces`;await new Promise(r=>setTimeout(r,0))}}await Promise.all(Array.from({length:Math.min(3,atlas.chunks.length)},worker));state.ready=true;loading.hidden=true;state.visible=new Set(SYSTEMS.filter(s=>atlas.systemStats?.[s.id]&&s.id!=='integumentary').map(s=>s.id));renderSystems();rebuildLayout();updateSceneState();fitView('three-quarter',0)}

let last=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;controls.update();if(Math.abs(state.explode-state.targetExplode)>.0001){state.explode=THREE.MathUtils.damp(state.explode,state.targetExplode,8,dt);updateSceneState()}renderer.render(scene,camera)}requestAnimationFrame(animate);

(async()=>{try{const r=await fetch('/models/atlas.json',{cache:'no-cache'});if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');const atlas=await r.json();if(atlas.parts?.length!==2234)throw new Error(`Expected 2,234 source meshes, received ${atlas.parts?.length||0}.`);await loadAtlas(atlas)}catch(error){console.error(error);loadingCopy.textContent=error.message||'Could not load anatomy';loadingBar.style.background='#b95345'}})();
