import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const DEFAULT_COLORS={skeletal:'#d8cfb6',muscular:'#a85b50',arterial:'#b95345',venous:'#527c9f',nervous:'#d8b565',respiratory:'#b98991',digestive:'#b8916b',urinary:'#88738f',reproductive:'#bda098',lymphatic:'#879f7c',endocrine:'#c5a09a',sensory:'#91aeb2',cardiac:'#9d4f45',connective:'#aec3bb',integumentary:'#ba9b7d',other:'#9da5a3'};
const SYSTEM_NAMES={skeletal:'Skeletal',muscular:'Muscular',arterial:'Arterial',venous:'Venous',nervous:'Nervous',respiratory:'Respiratory',digestive:'Digestive',urinary:'Urinary',reproductive:'Reproductive',lymphatic:'Lymphatic',endocrine:'Endocrine',sensory:'Sensory',cardiac:'Cardiac',connective:'Connective tissue',integumentary:'Body surface',other:'Other anatomy'};
const SYSTEM_SUMMARY={skeletal:'Structural anatomy that supports and protects the body.',muscular:'Muscular anatomy involved in movement and stability.',arterial:'Arterial anatomy carrying blood away from the heart.',venous:'Venous anatomy returning blood toward the heart.',nervous:'Neural anatomy involved in signaling, sensation and control.',respiratory:'Anatomy involved in conducting air and gas exchange.',digestive:'Anatomy involved in digestion and nutrient processing.',urinary:'Anatomy involved in filtration, urine transport and storage.',reproductive:'Male reproductive anatomy in the source reference model.',lymphatic:'Lymphatic and immune-associated anatomy.',endocrine:'Hormone-producing anatomy.',sensory:'Anatomy associated with special senses.',cardiac:'Structures of the heart and cardiac apparatus.',connective:'Supporting connective tissues.',integumentary:'Body-surface anatomy.',other:'An anatomical structure from the source atlas.'};
const MODE_COPY={explore:'Survey · anatomy stays assembled',reveal:'Dissect · stable reveal around the selected structure',xray:'Ghost · selected anatomy remains solid',relate:'Lineage · mapped hierarchy in context'};
const ANCHOR_TERMS=['brain','heart','left lung','right lung','liver','stomach','left kidney','right kidney','left femur','right femur','spinal cord'];
const LOWER_WORDS=['femur','tibia','fibula','patella','knee','ankle','foot','toe','calcane','talus','tarsal','metatars','plantaris','gastrocnem','soleus','sartorius','quadriceps','hamstring','iliotibial','perone','poplite'];
const UPPER_WORDS=['humerus','radius','ulna','elbow','wrist','hand','finger','carpal','metacarp','brachial','forearm','biceps','triceps','deltoid','cephalic vein'];
const HEAD_WORDS=['brain','skull','cranial','cerebr','cerebell','eye','orbit','ear','cochlea','mandible','maxilla','facial','head','scalp','tongue','pharynx'];
const PELVIS_WORDS=['pelvis','pelvic','prostate','bladder','rectum','testis','penis','seminal','sacrum','coccyx'];

const state={mode:'explore',depth:36,labels:true,selectedIndex:null,related:new Set(),atlas:null,ready:false,overlayToken:0,presentationAnimating:false,revealPlan:new Map()};
const host=document.querySelector('#scene'),labelsLayer=document.querySelector('#labels-layer'),badge=document.querySelector('.prototype-badge'),nameEl=document.querySelector('#structure-name'),metaEl=document.querySelector('#structure-meta'),summaryEl=document.querySelector('#structure-summary'),card=document.querySelector('#structure-card'),depth=document.querySelector('#depth'),depthOutput=document.querySelector('#depth-output'),depthRow=document.querySelector('#depth-row'),app=document.querySelector('#app'),deckCopy=document.querySelector('.deck-heading small');

const scene=new THREE.Scene();scene.background=new THREE.Color('#eee9df');scene.fog=new THREE.Fog('#eee9df',5.2,13.5);
const camera=new THREE.PerspectiveCamera(34,1,.01,50);camera.position.set(.3,1.25,3.6);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Human Atlas 3D anatomy. Drag to orbit, scroll or pinch to zoom, and select a structure to inspect it.');
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.9,0);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=.12;controls.maxDistance=14;controls.maxPolarAngle=Math.PI*.98;
scene.add(new THREE.HemisphereLight(0xfffbf1,0x918b82,1.9));const key=new THREE.DirectionalLight(0xffffff,2.8);key.position.set(-3,5,5);scene.add(key);const fill=new THREE.DirectionalLight(0xe7f4ef,.8);fill.position.set(4,2,2);scene.add(fill);const rim=new THREE.DirectionalLight(0xbcdedc,1.0);rim.position.set(3,2,-4);scene.add(rim);
const floor=new THREE.Mesh(new THREE.CircleGeometry(2.15,96),new THREE.MeshStandardMaterial({color:'#d9d1c5',roughness:.98}));floor.rotation.x=-Math.PI/2;floor.position.y=-.018;scene.add(floor);const ring=new THREE.Mesh(new THREE.RingGeometry(1.2,1.212,128),new THREE.MeshBasicMaterial({color:'#8e7c64',transparent:true,opacity:.2,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=-.004;scene.add(ring);

const batches=new Map(),handles=[],partCenters=[],partRadii=[],currentOffsets=[],conceptById=new Map(),elementToIndices=new Map();const focusGroup=new THREE.Group();focusGroup.renderOrder=20;scene.add(focusGroup);let needLabels=true,lastLabelUpdate=0;const identity=new THREE.Matrix4(),matrix=new THREE.Matrix4(),zero=new THREE.Vector3(),temp=new THREE.Vector3(),cameraRight=new THREE.Vector3(),cameraUp=new THREE.Vector3(),cameraForward=new THREE.Vector3();

new ResizeObserver(()=>{const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);needLabels=true}).observe(host);controls.addEventListener('change',()=>{needLabels=true});

async function fetchBinary(url){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw new Error(`Could not load ${url} (${r.status})`);const ab=await r.arrayBuffer(),bytes=new Uint8Array(ab);if(bytes[0]===0x1f&&bytes[1]===0x8b){if(typeof DecompressionStream==='undefined')throw new Error('This browser cannot decompress the anatomy package. Please use a current Chrome, Edge, Safari, or Firefox.');const stream=new Blob([ab]).stream().pipeThrough(new DecompressionStream('gzip'));return new Response(stream).arrayBuffer()}return ab}
function colorFor(system){return state.atlas?.systemColors?.[system]||DEFAULT_COLORS[system]||DEFAULT_COLORS.other}function systemName(system){return SYSTEM_NAMES[system]||system||'Anatomy'}
function centerAndRadius(bounds){const a=bounds[0],b=bounds[1],c=new THREE.Vector3((a[0]+b[0])/2,(a[1]+b[1])/2,(a[2]+b[2])/2),r=Math.max(.002,Math.hypot(b[0]-a[0],b[1]-a[1],b[2]-a[2])/2);return[c,r]}
function createBatches(atlas){for(const[system,s]of Object.entries(atlas.systemStats||{})){const mat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:system==='skeletal'?.67:.57,metalness:.015,transparent:false,opacity:1,side:THREE.DoubleSide});const batch=new THREE.BatchedMesh(Math.max(1,s.parts+2),Math.ceil(s.vertices*1.01)+16,Math.ceil(s.indices*1.01)+48,mat);batch.frustumCulled=false;batch.perObjectFrustumCulled=true;batch.userData.instanceToPart=[];batches.set(system,batch);scene.add(batch)}}
function geometryFromPart(buffer,p){const g=new THREE.BufferGeometry(),pos=new Float32Array(buffer,p.positions,p.vertexCount*3),normal=new Int16Array(buffer,p.normals,p.vertexCount*3),index=new Uint32Array(buffer,p.indices,p.indexCount);g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('normal',new THREE.BufferAttribute(normal,3,true));g.setIndex(new THREE.BufferAttribute(index,1));g.boundingBox=new THREE.Box3(new THREE.Vector3(...p.bounds[0]),new THREE.Vector3(...p.bounds[1]));g.computeBoundingSphere();return g}

async function loadAtlas(atlas){state.atlas=atlas;atlas.parts.forEach((p,i)=>{const[c,r]=centerAndRadius(p.bounds);partCenters[i]=c;partRadii[i]=r;currentOffsets[i]=new THREE.Vector3();const eid=String(p.elementId||p.id||'').toUpperCase();if(!elementToIndices.has(eid))elementToIndices.set(eid,[]);elementToIndices.get(eid).push(i)});atlas.concepts?.forEach(c=>conceptById.set(c.id,c));createBatches(atlas);const byChunk=Array.from({length:atlas.chunks.length},()=>[]);atlas.parts.forEach((p,i)=>byChunk[p.chunk].push([i,p]));let loaded=0,cursor=0;async function worker(){while(cursor<atlas.chunks.length){const ci=cursor++,buffer=await fetchBinary(atlas.chunks[ci].url);for(const[i,p]of byChunk[ci]){const batch=batches.get(p.system);if(!batch)continue;const g=geometryFromPart(buffer,p),gid=batch.addGeometry(g),iid=batch.addInstance(gid);batch.setColorAt(iid,new THREE.Color(colorFor(p.system)));batch.setMatrixAt(iid,identity);batch.userData.instanceToPart[iid]=i;handles[i]={batch,instanceId:iid,geometryId:gid};g.dispose()}loaded++;badge.textContent=`Loading BodyParts3D · ${Math.round(loaded/atlas.chunks.length*100)}%`;await new Promise(r=>setTimeout(r,0))}}await Promise.all(Array.from({length:Math.min(3,atlas.chunks.length)},worker));state.ready=true;badge.textContent=`${atlas.parts.length.toLocaleString()} verified meshes · ${atlas.version}`;badge.classList.add('source-ready');restoreBaseMaterials();fitWholeBody();updateModeUI();needLabels=true}
function bodyMetrics(){const b=state.atlas.bounds;return{low:b[0],high:b[1],height:b[1][1]-b[0][1],width:b[1][0]-b[0][0]}}
function fitWholeBody(){if(!state.atlas)return;const{low,high,height}=bodyMetrics(),c=new THREE.Vector3((low[0]+high[0])/2,(low[1]+high[1])/2,(low[2]+high[2])/2);controls.target.copy(c).add(new THREE.Vector3(0,height*.025,0));camera.position.copy(c).add(new THREE.Vector3(height*.22,height*.05,height*1.86));controls.update()}
function includesAny(name,words){const n=name.toLowerCase();return words.some(w=>n.includes(w))}
function displayRegion(part,index){const n=part.name||'',center=partCenters[index];if(includesAny(n,HEAD_WORDS))return'head & neck';if(includesAny(n,UPPER_WORDS))return'upper limb';if(includesAny(n,LOWER_WORDS))return'lower limb';if(includesAny(n,PELVIS_WORDS))return'pelvis';const{low,high,height,width}=bodyMetrics(),y=(center.y-low[1])/height,x=Math.abs(center.x-(low[0]+high[0])/2)/Math.max(.001,width);if(y>=.80)return'head & neck';if(x>.27&&y>=.40&&y<.80)return'upper limb';if(y<.40)return'lower limb';if(y<.49)return'pelvis';if(y<.62)return'abdomen';return'thorax'}
function conceptRelations(index){const p=state.atlas.parts[index],c=conceptById.get(p.conceptId),out=new Set();if(!c)return out;for(const cid of[c.parentId,...(c.children||[])].filter(Boolean)){const rc=conceptById.get(cid);for(const eid of rc?.elements||[])for(const ri of elementToIndices.get(String(eid).toUpperCase())||[])if(ri!==index)out.add(ri)}return out}
function selectPart(index,{focus=false}={}){if(!state.atlas||index==null||!state.atlas.parts[index])return;state.selectedIndex=index;state.related=conceptRelations(index);const p=state.atlas.parts[index],sourceId=p.elementId||p.id;nameEl.textContent=p.name;metaEl.textContent=`${systemName(p.system)} · ${displayRegion(p,index)}${sourceId?` · ${sourceId}`:''}`;summaryEl.textContent=SYSTEM_SUMMARY[p.system]||SYSTEM_SUMMARY.other;card.classList.add('visible');app.classList.add('has-selection');if(focus)focusPart(index);if(state.mode==='reveal')computeRevealPlan();else state.revealPlan.clear();applyModeLayer();state.presentationAnimating=true;needLabels=true}
function clearSelection(){state.selectedIndex=null;state.related.clear();state.revealPlan.clear();card.classList.remove('visible');app.classList.remove('has-selection');applyModeLayer();state.presentationAnimating=true;needLabels=true}
function focusPart(index){const c=partCenters[index].clone().add(currentOffsets[index]||zero),r=partRadii[index],dir=camera.position.clone().sub(controls.target).normalize();controls.target.copy(c);camera.position.copy(c).addScaledVector(dir,Math.max(.34,Math.min(3,r*7.4)));controls.update()}
function pickBest(term,{focus=true}={}){if(!state.atlas)return;const q=term.toLowerCase();let best=-1,score=-Infinity;state.atlas.parts.forEach((p,i)=>{const n=p.name.toLowerCase();let s=n===q?1200:n.startsWith(q)?900:n.includes(q)?560:0;s+=Math.log10(partRadii[i]+1e-5)*10;if(s>score){score=s;best=i}});if(best>=0&&score>0)selectPart(best,{focus})}
function focusRegion(region){if(!state.atlas)return;let box=null,count=0;state.atlas.parts.forEach((p,i)=>{if(displayRegion(p,i)!==region)return;const b=new THREE.Box3(new THREE.Vector3(...p.bounds[0]),new THREE.Vector3(...p.bounds[1]));box=box?box.union(b):b;count++});if(!box||!count)return;clearSelection();setMode('explore');const size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);const extent=Math.max(size.x,size.y,size.z,.18),dir=camera.position.clone().sub(controls.target).normalize();controls.target.copy(center);camera.position.copy(center).addScaledVector(dir,THREE.MathUtils.clamp(extent*2.3,.7,4.2));controls.update();needLabels=true}
function updateModeUI(){document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));document.querySelectorAll('[data-card-mode]').forEach(b=>b.classList.toggle('active',b.dataset.cardMode===state.mode));if(deckCopy)deckCopy.textContent=MODE_COPY[state.mode]||'Change how spatial context is shown';depthRow.hidden=state.mode!=='reveal'}
function showModeNote(text){let note=document.querySelector('.mode-note');if(!note){note=document.createElement('div');note.className='mode-note';app.appendChild(note)}note.textContent=text;note.classList.add('visible');clearTimeout(showModeNote.timer);showModeNote.timer=setTimeout(()=>note.classList.remove('visible'),1800)}
function setMode(mode){if(mode==='trace')return;if(mode!=='explore'&&state.selectedIndex==null){showModeNote('Select a structure first, then choose this lens.');return}state.mode=mode;if(mode==='reveal')computeRevealPlan();else state.revealPlan.clear();updateModeUI();applyModeLayer();state.presentationAnimating=true;needLabels=true}

function computeRevealPlan(){state.revealPlan.clear();const selected=state.selectedIndex;if(selected==null)return;const sc=partCenters[selected],sr=partRadii[selected],sndc=sc.clone().project(camera),sd=camera.position.distanceTo(sc);camera.getWorldDirection(cameraForward).normalize();cameraRight.crossVectors(cameraForward,camera.up).normalize();cameraUp.crossVectors(cameraRight,cameraForward).normalize();const candidates=[];for(let i=0;i<state.atlas.parts.length;i++){if(i===selected||!handles[i])continue;const c=partCenters[i],d=camera.position.distanceTo(c),ndc=c.clone().project(camera);if(ndc.z<-1||ndc.z>1)continue;const dx=ndc.x-sndc.x,dy=ndc.y-sndc.y,nd=Math.hypot(dx,dy),threshold=Math.max(.04,((partRadii[i]+sr)/Math.max(.12,sd))*1.45),inFront=d<sd-Math.min(.01,sr*.08);if(!inFront||nd>threshold)continue;let sx=dx,sy=dy;if(Math.hypot(sx,sy)<.014){const angle=((i*137.508)%360)*Math.PI/180;sx=Math.cos(angle);sy=Math.sin(angle)*.7}const length=Math.hypot(sx,sy)||1;sx/=length;sy/=length;const direction=new THREE.Vector3().addScaledVector(cameraRight,sx).addScaledVector(cameraUp,sy).normalize(),magnitude=THREE.MathUtils.clamp(.025+sr*.42+partRadii[i]*.08,.025,.12),overlap=1-Math.min(1,nd/threshold),depthScore=Math.max(0,(sd-d)/Math.max(.1,sd));candidates.push({index:i,score:overlap*.8+depthScore*.2,vector:direction.multiplyScalar(magnitude)})}candidates.sort((a,b)=>b.score-a.score);for(const c of candidates.slice(0,36))state.revealPlan.set(c.index,c.vector)}
function clearFocusOverlays(){state.overlayToken++;for(const mesh of[...focusGroup.children]){focusGroup.remove(mesh);mesh.geometry?.dispose();mesh.material?.dispose()}}
function restoreInstanceVisibility(){for(const h of handles)if(h?.batch?.setVisibleAt)h.batch.setVisibleAt(h.instanceId,true)}
function restoreBaseMaterials(){for(const[system,batch]of batches){batch.visible=system!=='integumentary';batch.material.transparent=false;batch.material.opacity=1;batch.material.depthWrite=true;batch.material.needsUpdate=true}}
function setContextOpacity(opacity){for(const[system,batch]of batches){if(system==='integumentary')continue;batch.visible=true;batch.material.transparent=true;batch.material.opacity=opacity;batch.material.depthWrite=opacity>=.42;batch.material.needsUpdate=true}}
async function buildFocusOverlays(indices){const token=++state.overlayToken,unique=[...new Set(indices)].filter(i=>i!=null&&handles[i]),byChunk=new Map();for(const i of unique){const p=state.atlas.parts[i];if(!byChunk.has(p.chunk))byChunk.set(p.chunk,[]);byChunk.get(p.chunk).push(i)}for(const[ci,partIndices]of byChunk){const buffer=await fetchBinary(state.atlas.chunks[ci].url);if(token!==state.overlayToken)return;for(const i of partIndices){const p=state.atlas.parts[i],g=geometryFromPart(buffer,p),selected=i===state.selectedIndex,color=new THREE.Color(colorFor(p.system));color.lerp(new THREE.Color(selected?'#65c9c0':'#4f9d99'),selected?.62:.32);const mat=new THREE.MeshStandardMaterial({color,roughness:.44,metalness:.015,side:THREE.DoubleSide,emissive:selected?new THREE.Color('#173d3a'):new THREE.Color('#000000'),emissiveIntensity:selected?.18:0}),mesh=new THREE.Mesh(g,mat);mesh.position.copy(currentOffsets[i]);mesh.userData.partIndex=i;focusGroup.add(mesh)}}}
function applyModeLayer(){if(!state.ready)return;clearFocusOverlays();restoreInstanceVisibility();restoreBaseMaterials();const selected=state.selectedIndex;if(selected==null)return;const selectedHandle=handles[selected];if(state.mode==='xray'){setContextOpacity(.11+(1-state.depth/100)*.09);selectedHandle?.batch?.setVisibleAt?.(selectedHandle.instanceId,false);buildFocusOverlays([selected]).catch(console.error);return}if(state.mode==='relate'){setContextOpacity(.085);const related=[...state.related].sort((a,b)=>partRadii[b]-partRadii[a]).slice(0,18),overlay=[selected,...related];for(const i of overlay)handles[i]?.batch?.setVisibleAt?.(handles[i].instanceId,false);buildFocusOverlays(overlay).catch(console.error);return}selectedHandle?.batch?.setVisibleAt?.(selectedHandle.instanceId,false);buildFocusOverlays([selected]).catch(console.error)}
function targetOffsetFor(i){if(state.mode!=='reveal'||state.selectedIndex==null)return zero;const base=state.revealPlan.get(i);return base?temp.copy(base).multiplyScalar(state.depth/100):zero}
function updatePresentation(){if(!state.ready)return;let maxDelta=0;for(let i=0;i<state.atlas.parts.length;i++){const p=state.atlas.parts[i],h=handles[i];if(!h)continue;const color=new THREE.Color(colorFor(p.system));if(i===state.selectedIndex)color.lerp(new THREE.Color('#65c9c0'),.62);else if(state.mode==='relate'&&state.related.has(i))color.lerp(new THREE.Color('#4f9d99'),.35);h.batch.setColorAt(h.instanceId,color);const target=targetOffsetFor(i).clone(),before=currentOffsets[i].distanceTo(target);currentOffsets[i].lerp(target,.16);maxDelta=Math.max(maxDelta,before);matrix.makeTranslation(currentOffsets[i].x,currentOffsets[i].y,currentOffsets[i].z);h.batch.setMatrixAt(h.instanceId,matrix)}for(const overlay of focusGroup.children){const i=overlay.userData.partIndex;if(i!=null)overlay.position.copy(currentOffsets[i])}state.presentationAnimating=maxDelta>.00025;needLabels=true}

function isAnchorName(name){const n=name.toLowerCase();return ANCHOR_TERMS.some(term=>n===term||n.includes(term))}
function updateLabels(){if(!state.ready||!state.labels){labelsLayer.replaceChildren();return}const w=host.clientWidth,h=host.clientHeight,cameraDistance=camera.position.distanceTo(controls.target),far=cameraDistance>2.25,mid=cameraDistance>1.0,candidates=[];for(let i=0;i<state.atlas.parts.length;i++){const p=state.atlas.parts[i],selected=i===state.selectedIndex,related=state.related.has(i),anchor=isAnchorName(p.name||'');if(far&&!selected&&!anchor)continue;if(state.mode==='relate'&&state.selectedIndex!=null&&!selected&&!related)continue;const center=partCenters[i].clone().add(currentOffsets[i]),ndc=center.project(camera);if(ndc.z<-1||ndc.z>1||Math.abs(ndc.x)>1.08||Math.abs(ndc.y)>1.08)continue;const distance=camera.position.distanceTo(center),screenSize=partRadii[i]/Math.max(.01,distance)*900;let priority=screenSize+(selected?10000:0)+(anchor?850:0)+(state.mode==='relate'&&related?1000:0);if((p.name||'').length<26)priority+=10;candidates.push({i,p,x:(ndc.x*.5+.5)*w,y:(-ndc.y*.5+.5)*h,priority,screenSize,selected})}candidates.sort((a,b)=>b.priority-a.priority);const limit=state.mode==='relate'?18:far?7:mid?12:24,placed=[],accepted=[];for(const c of candidates){if(accepted.length>=limit&&!c.selected)continue;if(!c.selected&&c.screenSize<1.35&&!far)continue;const collision=placed.some(p=>Math.abs(p.x-c.x)<104&&Math.abs(p.y-c.y)<31);if(collision&&!c.selected)continue;placed.push(c);accepted.push(c)}const frag=document.createDocumentFragment();for(const l of accepted){const btn=document.createElement('button');btn.className='living-label'+(l.selected?' selected':'');btn.style.left=l.x+'px';btn.style.top=l.y+'px';btn.innerHTML=`<span class="label-line"></span><span class="label-text"><strong>${escapeHtml(l.p.name)}</strong>${l.selected?`<small>${systemName(l.p.system)} · ${displayRegion(l.p,l.i)}</small>`:''}</span>`;btn.addEventListener('click',e=>{e.stopPropagation();selectPart(l.i)});frag.appendChild(btn)}labelsLayer.replaceChildren(frag);needLabels=false}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null;renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(!state.ready||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const overlayHits=raycaster.intersectObjects(focusGroup.children,false);if(overlayHits.length&&overlayHits[0].object.userData.partIndex!=null){selectPart(overlayHits[0].object.userData.partIndex);return}const hits=raycaster.intersectObjects([...batches.values()],false),hit=hits.find(x=>(x.batchId??x.instanceId)!=null);if(hit){const id=hit.batchId??hit.instanceId,index=hit.object.userData.instanceToPart[id];if(index!=null)selectPart(index)}});

document.querySelector('#clear-selection').addEventListener('click',clearSelection);document.querySelector('#focus-selection').addEventListener('click',()=>{if(state.selectedIndex!=null)focusPart(state.selectedIndex)});document.querySelector('#home-view').addEventListener('click',()=>{clearSelection();setMode('explore');fitWholeBody()});document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));document.querySelectorAll('[data-card-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.cardMode)));document.querySelectorAll('[data-region]').forEach(b=>b.addEventListener('click',()=>focusRegion(b.dataset.region)));
depth.addEventListener('input',()=>{state.depth=Number(depth.value);depthOutput.textContent=state.depth+'%';state.presentationAnimating=true;needLabels=true});const labelsToggle=document.querySelector('#labels-toggle');labelsToggle.addEventListener('click',()=>{state.labels=!state.labels;labelsToggle.classList.toggle('active',state.labels);needLabels=true});
const searchModal=document.querySelector('#search-modal'),aboutModal=document.querySelector('#about-modal'),searchInput=document.querySelector('#search-input'),searchResults=document.querySelector('#search-results');function renderSearch(){const q=searchInput.value.trim().toLowerCase();if(!state.atlas)return;const results=state.atlas.parts.map((p,i)=>({p,i})).filter(({p,i})=>!q||p.name.toLowerCase().includes(q)||String(p.elementId||'').toLowerCase().includes(q)||String(p.conceptId||'').toLowerCase().includes(q)||systemName(p.system).toLowerCase().includes(q)||displayRegion(p,i).includes(q)).sort((a,b)=>partRadii[b.i]-partRadii[a.i]).slice(0,18);searchResults.replaceChildren(...results.map(({p,i})=>{const b=document.createElement('button'),sourceId=p.elementId||p.id||'';b.innerHTML=`<span class="system-dot" style="background:${colorFor(p.system)}"></span><span><strong>${escapeHtml(p.name)}</strong><small>${systemName(p.system)} · ${displayRegion(p,i)}${sourceId?` · ${escapeHtml(sourceId)}`:''}</small></span>`;b.addEventListener('click',()=>{selectPart(i,{focus:true});searchModal.hidden=true});return b}))}
document.querySelector('#search-open').addEventListener('click',()=>{searchModal.hidden=false;searchInput.focus();renderSearch()});document.querySelector('#about-open').addEventListener('click',()=>aboutModal.hidden=false);searchInput.addEventListener('input',renderSearch);document.querySelectorAll('[data-close="search"]').forEach(b=>b.addEventListener('click',()=>searchModal.hidden=true));document.querySelectorAll('[data-close="about"]').forEach(b=>b.addEventListener('click',()=>aboutModal.hidden=true));searchModal.addEventListener('pointerdown',e=>{if(e.target===searchModal)searchModal.hidden=true});aboutModal.addEventListener('pointerdown',e=>{if(e.target===aboutModal)aboutModal.hidden=true});window.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement?.tagName!=='INPUT'){e.preventDefault();searchModal.hidden=false;searchInput.focus();renderSearch()}if(e.key==='Escape'){searchModal.hidden=true;aboutModal.hidden=true}});
function startFallback(message){badge.textContent='Anatomy package unavailable';const note=document.createElement('div');note.className='build-note';note.textContent=message;host.appendChild(note);state.ready=false}
function animate(t){requestAnimationFrame(animate);controls.update();if(state.presentationAnimating)updatePresentation();renderer.render(scene,camera);if(state.ready&&needLabels&&t-lastLabelUpdate>90){updateLabels();lastLabelUpdate=t}}requestAnimationFrame(animate);
(async()=>{try{badge.textContent='Loading verified BodyParts3D package…';const res=await fetch('/models/atlas.json',{cache:'no-cache'});if(!res.ok)throw new Error('The verified anatomy package could not be loaded.');const atlas=await res.json();if(atlas.version!=='BodyParts3D 4.0'||atlas.parts?.length!==2234)throw new Error('The anatomy manifest did not pass the 2,234-part source gate.');await loadAtlas(atlas)}catch(err){console.error(err);startFallback(err instanceof Error?err.message:'The anatomy package is not ready yet.')}})();
